### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by kamalhm** [cuikangyi/Dell-Inspiron-14-7460-Hackintosh#1]
What is the spec of your 7460? Can you make a short guide on how to do it on the readme?

**Comment by cuikangyi** [comment]
|  | |
| -------- | ------------------------------------------------------------ |
| model | Dell Inspiron 7460 |
| cpu | Intel Core i5-7200U |
| memory | 8 GB|
| graphics card | Intel HD Graphics 620|
| audio card | ALC256|
| network card | Intel ac7265 (replace by bcm94360cs2) |

**Comment by kamalhm** [comment]
thanks! seems like just like mine
