### ISSUE TITLE
What is the version of your Mac system?

### ISSUE THREAD

**Issue by zhudpos** [cuikangyi/Dell-Inspiron-14-7460-Hackintosh#2]
What is the version of your Mac system? Can you make a short guide on the readme?

**Comment by cuikangyi** [comment]
##### macOS Catalina  10.15
需要修改bios配置
- 关闭cfg
- 修改dvmt为64M

不想修改bios的话需要修改参数，具体你可以看下oc的文档

**Comment by zhudpos** [comment]
ok， thanks
